changes to generate undefined reference to symbol in the vtv_init library
git-svn-id: svn+ssh://gcc.gnu.org/svn/gcc/branches/google/gcc-4_6-mobile-vtable-security@192579 138bc75d-0d04-0410-961f-82ee72b054a4